{{- $fullName := include "elastic-alertmanager-connector.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-deployment
  labels:
     {{- include "elastic-alertmanager-connector.labels" . | nindent 4 }}  
spec:
  selector:
    matchLabels:
      {{- include "elastic-alertmanager-connector.selectorLabels" . | nindent 6 }}  
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "elastic-alertmanager-connector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ $fullName }}-container
          {{- with .Values.image }}
          image: {{ .registry }}/{{ .repository }}:{{ .tag }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- if .pullSecrets }}
            {{- toYaml .pullSecrets | nindent 8 }}
          {{- end }}
          {{- end }}          
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ES_HOST
              value: {{ required "You must supply host address for the server" .Values.server.host | quote }}
            - name: INDEX_NAME
              value: {{ required "You must supply the index for data writes of the server" .Values.server.index | quote }}
            - name: FLASK_PORT
              value: '8080'
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secret
                  key: username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secret
                  key: password
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}                  
