{{- $fullName := include "elastic-alertmanager-connector.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  labels:
     {{- include "elastic-alertmanager-connector.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.server.username | b64enc | quote }}
  password: {{ .Values.server.password | b64enc | quote }}
