{{- $fullName := include "elastic-alertmanager-connector.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service
  labels:
    {{- include "elastic-alertmanager-connector.labels" . | nindent 4 }}  
spec:
  selector:
    {{- include "elastic-alertmanager-connector.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
